version: '3.3'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./_volume/mongodb/data:/data/db
  redis:
    image: redis:latest
    volumes:
      - ./_volume/redis/data:/data
    restart: always
    ports:
      - "6379:6379"
